apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal
  namespace: default
  labels:
    app: admin-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      containers:
        - name: admin-portal
          image: ghcr.io/udaarash23/university-portal-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: admin-portal-secrets
          env:
            - name: NODE_ENV
              value: "production"
