apiVersion: v1
kind: Service
metadata:
  name: library-portal
  namespace: default
spec:
  selector:
    app: library-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
