apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-portal
  namespace: default
  labels:
    app: student-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-portal
  template:
    metadata:
      labels:
        app: student-portal
    spec:
      containers:
        - name: student-portal
          image: ghcr.io/udaarash23/university-portal-student:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: student-portal-secrets
          env:
            - name: NODE_ENV
              value: "production"
            - name: AUTH_TRUST_HOST
              value: "true"
            - name: NEXTAUTH_URL
              value: "https://student.local"
            - name: WSO2_CLIENT_ID
              value: "zEGJGcPPI4WasI1Qbcts8A8gCwca"
            - name: WSO2_CLIENT_SECRET
              value: "CcQKQsCYHfN3tA2SwCWZM36fxRgdMWjkLYcIE0GzNfsa"
            - name: WSO2_ISSUER
              value: "https://wso2-is-identity-server.wso2is.svc.cluster.local:9443/oauth2/token"
            - name: WSO2_WELL_KNOWN
              value: "https://wso2-is-identity-server.wso2is.svc.cluster.local:9443/oauth2/oidcdiscovery/.well-known/openid-configuration"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
