// Author: System
// Project: University-Portal
// FP-ID: FP-20260105-ERR-CODES
// FP-HASH: HASH-PLACEHOLDER
// Generated: 2026-01-05T10:55:00Z

const __FP_SIG = "FP-20260105-ERR-CODES|HASH-PLACEHOLDER";

/**
 * Global Error Codes
 *
 * Single source of truth for all application error codes.
 * varying from generic HTTP-like errors to specific domain context errors.
 *
 * Used by:
 * - Backend: To throw specific typed errors
 * - Frontend: To handle errors and show localized messages
 */
export const ERROR_CODES = {
  // Generic
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DB_FAILURE: "DB_FAILURE",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  // Student Context
  STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
  STUDENT_ALREADY_EXISTS: "STUDENT_ALREADY_EXISTS",

  // User Context
  USER_NOT_FOUND: "USER_NOT_FOUND",

  // Academics Context
  COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
  COURSE_ALREADY_EXISTS: "COURSE_ALREADY_EXISTS",
  OFFERING_NOT_FOUND: "OFFERING_NOT_FOUND",
  OFFERING_ALREADY_EXISTS: "OFFERING_ALREADY_EXISTS",
  DEGREE_PROGRAM_NOT_FOUND: "DEGREE_PROGRAM_NOT_FOUND",
  DEPARTMENT_NOT_FOUND: "DEPARTMENT_NOT_FOUND",

  // Books Context
  BOOK_NOT_FOUND: "BOOK_NOT_FOUND",
  BOOK_ALREADY_EXISTS: "BOOK_ALREADY_EXISTS",
  BOOK_UNAVAILABLE: "BOOK_UNAVAILABLE",

  // Identity Context
  IDENTITY_SERVER_ERROR: "IDENTITY_SERVER_ERROR",
  IDENTITY_USER_NOT_FOUND: "IDENTITY_USER_NOT_FOUND",
  IDENTITY_CREATION_FAILED: "IDENTITY_CREATION_FAILED",

  // Lending Context
  LENDING_BOOK_UNAVAILABLE: "LENDING_BOOK_UNAVAILABLE",
  LENDING_STUDENT_NOT_REGISTERED: "LENDING_STUDENT_NOT_REGISTERED",
  LENDING_ALREADY_BORROWED: "LENDING_ALREADY_BORROWED",
  LENDING_RECORD_NOT_FOUND: "LENDING_RECORD_NOT_FOUND",
  LENDING_ALREADY_RETURNED: "LENDING_ALREADY_RETURNED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
